// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hobby_tracker_web_api.Database;

#nullable disable

namespace hobby_tracker_web_api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220925142309_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("hobby_tracker_web_api.Database.Entities.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HabitId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 1,
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 1,
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 1,
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 1,
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 1,
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 1,
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 2,
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 2,
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 2,
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 2,
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2022, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 2,
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2022, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HabitId = 2,
                            IsCompleted = false
                        });
                });

            modelBuilder.Entity("hobby_tracker_web_api.Database.Entities.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Achieved")
                        .HasColumnType("int");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Habits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Achieved = 6,
                            Goal = 10,
                            Name = "React"
                        },
                        new
                        {
                            Id = 2,
                            Achieved = 6,
                            Goal = 8,
                            Name = "React"
                        });
                });

            modelBuilder.Entity("hobby_tracker_web_api.Database.Entities.Day", b =>
                {
                    b.HasOne("hobby_tracker_web_api.Database.Entities.Habit", "Habit")
                        .WithMany("Days")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("hobby_tracker_web_api.Database.Entities.Habit", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
